package io.gatling.demo

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.util.Random
import scala.collection.mutable.ArrayBuffer

import scala.concurrent.duration._
import java.io.File

import com.typesafe.config.{Config, ConfigFactory}

class Lenguaje extends Simulation {

	val config = ConfigFactory.parseFile(new File("src/test/resources/data.conf"))

	val anws = ArrayBuffer[String]()

	def patern_anws() ={
		val src = scala.io.Source.fromFile("src/test/resources/anwser_patern.csv").getLines
		val headerLine = src.take(1).next

		for(l <- src) {
			// split line by comma and process them
			l.split(",").map { c =>
				anws+= c.toString
			}
		}
	}


	def rand_anws(): String = {
		var answers = Array("1", "2", "3", "4")
		var random_answer = "A" + answers(Random.nextInt(answers.length))
		return random_answer.toString
	}
	def rand_feed_anws()={
		for( w <- 0 to 100){
			anws+= rand_anws()
		}
	}

	if(config.getString("anw_rand").toInt== 0){
		patern_anws()
	}else{
		rand_feed_anws()
	}


	println(anws(1))
	println(anws(2))
	println(anws(3))


	var question_counter_offset = 2
	val nbUsers = Integer.getInteger("users", 1)
	val nbDuration = Integer.getInteger("Dmaxduration", 60)

	val httpProtocol = http
		.baseUrl(config.getString("url_base"))
		.userAgentHeader("Apache-HttpClient/4.5.5 (Java/1.8.0_191)")
		.header("Connection", "keep-alive")
		.disableCaching // no caching


	val scn = scenario("Lenguaje")
		.feed(csv("tokens_432483.csv").queue)
		.exec(flushCookieJar) // flush all cookies

		.exec(http("recover_token")
			.get(config.getString("url_post"))
			.check(css("input[name=\"YII_CSRF_TOKEN\"]","value").saveAs("YII"))
			.check(status.is(200))
		).pause(5.seconds,20.seconds)

		.exec(http("login")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("token", "${token}")
			.formParam("continue", "continue")
		).pause(5.seconds,20.seconds)

		.exec(http("recover_data_lime")
			.get(config.getString("url_post"))
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
			.check(css("#sid","value").saveAs("SID"))
		).pause(5.seconds,20.seconds)

		.exec(http("terms")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "")
			.formParam("sid", "${SID}")
			.formParam("lastgroupname", "_WELCOME_SCREEN_")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("thisstep", "0")
			.formParam("token", "${token}")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#start_time","value").saveAs("start_time"))
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
			.check(css("#fieldnames","value").saveAs("fieldnames"))
			.check(css("input[name=\"YII_CSRF_TOKEN\"]","value").saveAs("YII"))
		).pause(5.seconds,20.seconds)
		
		.exec(http("request_12")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X320X602")
			.formParam("thisstep", "1")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718916")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance602", "1")
			.formParam("relevanceG0", "1")
			.formParam("432483X320X602", anws(1))
			.formParam("lastgroup", "432483X320")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
			).pause(5.seconds,20.seconds)

		.exec(http("request_14")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X321X603")
			.formParam("thisstep", "2")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718919")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance603", "1")
			.formParam("relevanceG1", "1")
			.formParam("432483X321X603", anws(2))
			.formParam("lastgroup", "432483X321")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
			).pause(5.seconds,20.seconds)

		.exec(http("request_16")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X322X604")
			.formParam("thisstep", "3")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718922")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance604", "1")
			.formParam("relevanceG2", "1")
			.formParam("432483X322X604", anws(3))
			.formParam("lastgroup", "432483X322")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_18")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X323X605")
			.formParam("thisstep", "4")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718925")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance605", "1")
			.formParam("relevanceG3", "1")
			.formParam("432483X323X605", anws(4))
			.formParam("lastgroup", "432483X323")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_20")
			.post(config.getString("url_post"))
			
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X324X606")
			.formParam("thisstep", "5")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718928")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance606", "1")
			.formParam("relevanceG4", "1")
			.formParam("432483X324X606", anws(5))
			.formParam("lastgroup", "432483X324")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_22")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X404X686")
			.formParam("thisstep", "6")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718931")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance686", "1")
			.formParam("relevanceG5", "1")
			.formParam("432483X404X686", "pokemon")
			.formParam("lastgroup", "432483X404")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_24")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X328X610")
			.formParam("thisstep", "7")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718936")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance610", "1")
			.formParam("relevanceG6", "1")
			.formParam("432483X328X610", anws(6))
			.formParam("lastgroup", "432483X328")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_26")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X329X611")
			.formParam("thisstep", "8")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718939")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance611", "1")
			.formParam("relevanceG7", "1")
			.formParam("432483X329X611", anws(7))
			.formParam("lastgroup", "432483X329")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_28")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X405X687")
			.formParam("thisstep", "9")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718942")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance687", "1")
			.formParam("relevanceG8", "1")
			.formParam("432483X405X687", anws(8))
			.formParam("lastgroup", "432483X405")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_30")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X406X688")
			.formParam("thisstep", "10")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718945")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance688", "1")
			.formParam("relevanceG9", "1")
			.formParam("432483X406X688", anws(9))
			.formParam("lastgroup", "432483X406")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_32")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X361X643")
			.formParam("thisstep", "11")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718947")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance643", "1")
			.formParam("relevanceG10", "1")
			.formParam("432483X361X643", anws(10))
			.formParam("lastgroup", "432483X361")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_34")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X362X644")
			.formParam("thisstep", "12")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718950")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance644", "1")
			.formParam("relevanceG11", "1")
			.formParam("432483X362X644", anws(11))
			.formParam("lastgroup", "432483X362")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_36")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X363X645")
			.formParam("thisstep", "13")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718953")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance645", "1")
			.formParam("relevanceG12", "1")
			.formParam("432483X363X645", anws(12))
			.formParam("lastgroup", "432483X363")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_38")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X364X646")
			.formParam("thisstep", "14")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718956")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance646", "1")
			.formParam("relevanceG13", "1")
			.formParam("432483X364X646", anws(13))
			.formParam("lastgroup", "432483X364")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_40")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X331X613")
			.formParam("thisstep", "15")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718959")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance613", "1")
			.formParam("relevanceG14", "1")
			.formParam("432483X331X613", anws(14))
			.formParam("lastgroup", "432483X331")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_42")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X332X614")
			.formParam("thisstep", "16")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718962")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance614", "1")
			.formParam("relevanceG15", "1")
			.formParam("432483X332X614", anws(15))
			.formParam("lastgroup", "432483X332")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_44")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X333X615")
			.formParam("thisstep", "17")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718965")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance615", "1")
			.formParam("relevanceG16", "1")
			.formParam("432483X333X615", anws(16))
			.formParam("lastgroup", "432483X333")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_46")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X334X616")
			.formParam("thisstep", "18")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718967")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance616", "1")
			.formParam("relevanceG17", "1")
			.formParam("432483X334X616", anws(17))
			.formParam("lastgroup", "432483X334")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_48")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X335X617")
			.formParam("thisstep", "19")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718970")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance617", "1")
			.formParam("relevanceG18", "1")
			.formParam("432483X335X617", anws(18))
			.formParam("lastgroup", "432483X335")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_50")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X336X618")
			.formParam("thisstep", "20")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718974")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance618", "1")
			.formParam("relevanceG19", "1")
			.formParam("432483X336X618", anws(19))
			.formParam("lastgroup", "432483X336")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_52")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X337X619")
			.formParam("thisstep", "21")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718977")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance619", "1")
			.formParam("relevanceG20", "1")
			.formParam("432483X337X619", anws(20))
			.formParam("lastgroup", "432483X337")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_54")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X338X620")
			.formParam("thisstep", "22")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718980")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance620", "1")
			.formParam("relevanceG21", "1")
			.formParam("432483X338X620", "pokemon")
			.formParam("lastgroup", "432483X338")
			.formParam("ajax", "off")
			.formParam("move", "22")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_56")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X338X620")
			.formParam("thisstep", "22")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718985")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance620", "1")
			.formParam("relevanceG21", "1")
			.formParam("432483X338X620", "pokemon")
			.formParam("lastgroup", "432483X338")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_58")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X342X624")
			.formParam("thisstep", "23")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718988")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance624", "1")
			.formParam("relevanceG22", "1")
			.formParam("432483X342X624", anws(21))
			.formParam("lastgroup", "432483X342")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_60")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X343X625")
			.formParam("thisstep", "24")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718991")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance625", "1")
			.formParam("relevanceG23", "1")
			.formParam("432483X343X625", anws(22))
			.formParam("lastgroup", "432483X343")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_62")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X344X626")
			.formParam("thisstep", "25")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718993")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance626", "1")
			.formParam("relevanceG24", "1")
			.formParam("432483X344X626", anws(23))
			.formParam("lastgroup", "432483X344")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_64")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X345X627")
			.formParam("thisstep", "26")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718996")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance627", "1")
			.formParam("relevanceG25", "1")
			.formParam("432483X345X627", anws(24))
			.formParam("lastgroup", "432483X345")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_66")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X346X628")
			.formParam("thisstep", "27")
			.formParam("sid", "432483")
			.formParam("start_time", "1604718999")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance628", "1")
			.formParam("relevanceG26", "1")
			.formParam("432483X346X628", anws(25))
			.formParam("lastgroup", "432483X346")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_68")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X330X612")
			.formParam("thisstep", "28")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719001")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance612", "1")
			.formParam("relevanceG27", "1")
			.formParam("432483X330X612", anws(26))
			.formParam("lastgroup", "432483X330")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_70")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X347X629")
			.formParam("thisstep", "29")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719004")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance629", "1")
			.formParam("relevanceG28", "1")
			.formParam("432483X347X629", anws(27))
			.formParam("lastgroup", "432483X347")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_72")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X348X630")
			.formParam("thisstep", "30")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719007")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance630", "1")
			.formParam("relevanceG29", "1")
			.formParam("432483X348X630", anws(28))
			.formParam("lastgroup", "432483X348")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_74")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X349X631")
			.formParam("thisstep", "31")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719010")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance631", "1")
			.formParam("relevanceG30", "1")
			.formParam("432483X349X631", anws(29))
			.formParam("lastgroup", "432483X349")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_76")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X350X632")
			.formParam("thisstep", "32")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719013")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance632", "1")
			.formParam("relevanceG31", "1")
			.formParam("432483X350X632", anws(30))
			.formParam("lastgroup", "432483X350")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_78")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X351X633")
			.formParam("thisstep", "33")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719015")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance633", "1")
			.formParam("relevanceG32", "1")
			.formParam("432483X351X633", anws(31))
			.formParam("lastgroup", "432483X351")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_80")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X352X634")
			.formParam("thisstep", "34")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719018")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance634", "1")
			.formParam("relevanceG33", "1")
			.formParam("432483X352X634", anws(32))
			.formParam("lastgroup", "432483X352")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_82")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X356X638")
			.formParam("thisstep", "35")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719021")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance638", "1")
			.formParam("relevanceG34", "1")
			.formParam("432483X356X638", anws(33))
			.formParam("lastgroup", "432483X356")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_84")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X357X639")
			.formParam("thisstep", "36")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719024")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance639", "1")
			.formParam("relevanceG35", "1")
			.formParam("432483X357X639", anws(34))
			.formParam("lastgroup", "432483X357")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_86")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X358X640")
			.formParam("thisstep", "37")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719027")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance640", "1")
			.formParam("relevanceG36", "1")
			.formParam("432483X358X640", anws(35))
			.formParam("lastgroup", "432483X358")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_88")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X359X641")
			.formParam("thisstep", "38")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719030")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance641", "1")
			.formParam("relevanceG37", "1")
			.formParam("432483X359X641", anws(36))
			.formParam("lastgroup", "432483X359")
			.formParam("move", "movenext")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
			.formParam("ajax", "off")
		).pause(5.seconds,20.seconds)

		.exec(http("request_89")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "432483X360X642")
			.formParam("thisstep", "39")
			.formParam("sid", "432483")
			.formParam("start_time", "1604719030")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance641", "1")
			.formParam("relevanceG37", "1")
			.formParam("432483X360X642", "")
			.formParam("lastgroup", "432483X360")
			.formParam("move", "movesubmit")
			.formParam("ajax", "off"))

	setUp(scn.inject(atOnceUsers(config.getString("n_user").toInt))).protocols(httpProtocol)
}