package io.gatling.demo

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.util.Random
import scala.collection.mutable.ArrayBuffer

import scala.concurrent.duration._
import java.io.File

import com.typesafe.config.{Config, ConfigFactory}

class Matematica extends Simulation {

	val config = ConfigFactory.parseFile(new File("src/test/resources/data.conf"))

	val anws = ArrayBuffer[String]()

	def patern_anws() ={
		val src = scala.io.Source.fromFile("src/test/resources/anwser_patern.csv").getLines
		val headerLine = src.take(1).next

		for(l <- src) {
			// split line by comma and process them
			l.split(",").map { c =>
				anws+= c.toString
			}
		}
	}


	def rand_anws(): String = {
		var answers = Array("1", "2", "3", "4")
		var random_answer = "A" + answers(Random.nextInt(answers.length))
		return random_answer.toString
	}
	def rand_feed_anws()={
		for( w <- 0 to 100){
			anws+= rand_anws()
		}
	}

	if(config.getString("anw_rand").toInt== 0){
		patern_anws()
	}else{
		rand_feed_anws()
	}


	println(anws(1))
	println(anws(2))
	println(anws(3))


	var question_counter_offset = 2
	val nbUsers = Integer.getInteger("users", 1)
	val nbDuration = Integer.getInteger("Dmaxduration", 60)

	val httpProtocol = http
		.baseUrl(config.getString("url_base"))
		.userAgentHeader("Apache-HttpClient/4.5.5 (Java/1.8.0_191)")
		.header("Connection", "keep-alive")
		.disableCaching // no caching

	val scn = scenario("Matematica")
		.feed(csv("tokens_289647.csv").queue)
		.exec(flushCookieJar) // flush all cookies

		.exec(http("recover_token")
			.get(config.getString("url_post"))
			.check(css("input[name=\"YII_CSRF_TOKEN\"]","value").saveAs("YII"))
			.check(status.is(200))
		).pause(5.seconds,20.seconds)


		.exec(http("login")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("token", "${token}")
			.formParam("continue", "continue")
		).pause(5.seconds,20.seconds)

		.exec(http("recover_data_lime")
			.get(config.getString("url_post"))
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
			.check(css("#sid","value").saveAs("SID"))
		).pause(5.seconds,20.seconds)

		.exec(http("terms")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "")
			.formParam("sid", "${SID}")
			.formParam("lastgroupname", "_WELCOME_SCREEN_")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("thisstep", "0")
			.formParam("token", "${token}")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#start_time","value").saveAs("start_time"))
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
			.check(css("#fieldnames","value").saveAs("fieldnames"))
			.check(css("input[name=\"YII_CSRF_TOKEN\"]","value").saveAs("YII"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_3")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X229X501")
			.formParam("thisstep", "1")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709748")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance501", "1")
			.formParam("relevanceG0", "1")
			.formParam("289647X229X501", anws(1))
			.formParam("lastgroup", "289647X229")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_4")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X230X502")
			.formParam("thisstep", "2")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709752")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance502", "1")
			.formParam("relevanceG1", "1")
			.formParam("289647X230X502", anws(2))
			.formParam("lastgroup", "289647X230")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)
		.exec(http("request_5")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X231X503")
			.formParam("thisstep", "3")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709755")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance503", "1")
			.formParam("relevanceG2", "1")
			.formParam("289647X231X503", anws(3))
			.formParam("lastgroup", "289647X231")
			.formParam("move", "movenext")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_6")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X232X504")
			.formParam("thisstep", "4")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709758")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance504", "1")
			.formParam("relevanceG3", "1")
			.formParam("289647X232X504", anws(4))
			.formParam("lastgroup", "289647X232")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_7")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X233X505")
			.formParam("thisstep", "5")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709761")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance505", "1")
			.formParam("relevanceG4", "1")
			.formParam("289647X233X505", anws(5))
			.formParam("lastgroup", "289647X233")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_8")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X235X507")
			.formParam("thisstep", "6")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709765")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance507", "1")
			.formParam("relevanceG5", "1")
			.formParam("289647X235X507", anws(6))
			.formParam("lastgroup", "289647X235")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_9")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X236X508")
			.formParam("thisstep", "7")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709768")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance508", "1")
			.formParam("relevanceG6", "1")
			.formParam("289647X236X508", anws(7))
			.formParam("lastgroup", "289647X236")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)
		.exec(http("request_10")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X237X509")
			.formParam("thisstep", "8")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709771")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance509", "1")
			.formParam("relevanceG7", "1")
			.formParam("289647X237X509", anws(8))
			.formParam("lastgroup", "289647X237")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_11")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X238X510")
			.formParam("thisstep", "9")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709775")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance510", "1")
			.formParam("relevanceG8", "1")
			.formParam("289647X238X510", anws(9))
			.formParam("lastgroup", "289647X238")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_12")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X239X511")
			.formParam("thisstep", "10")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709778")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance511", "1")
			.formParam("relevanceG9", "1")
			.formParam("289647X239X511", anws(10))
			.formParam("lastgroup", "289647X239")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_13")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X240X512")
			.formParam("thisstep", "11")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709781")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance512", "1")
			.formParam("relevanceG10", "1")
			.formParam("289647X240X512", anws(11))
			.formParam("lastgroup", "289647X240")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_14")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X241X513")
			.formParam("thisstep", "12")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709784")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance513", "1")
			.formParam("relevanceG11", "1")
			.formParam("289647X241X513", anws(12))
			.formParam("lastgroup", "289647X241")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_15")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X242X514")
			.formParam("thisstep", "13")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709787")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance514", "1")
			.formParam("relevanceG12", "1")
			.formParam("289647X242X514", "pokemon")
			.formParam("lastgroup", "289647X242")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_16")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X243X515")
			.formParam("thisstep", "14")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709793")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance515", "1")
			.formParam("relevanceG13", "1")
			.formParam("289647X243X515", anws(13))
			.formParam("lastgroup", "289647X243")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_17")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X244X516")
			.formParam("thisstep", "15")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709796")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance516", "1")
			.formParam("relevanceG14", "1")
			.formParam("289647X244X516", anws(14))
			.formParam("lastgroup", "289647X244")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_18")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X245X517")
			.formParam("thisstep", "16")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709799")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance517", "1")
			.formParam("relevanceG15", "1")
			.formParam("289647X245X517", anws(15))
			.formParam("lastgroup", "289647X245")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_19")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X246X518")
			.formParam("thisstep", "17")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709802")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance518", "1")
			.formParam("relevanceG16", "1")
			.formParam("289647X246X518", anws(16))
			.formParam("lastgroup", "289647X246")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_20")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X247X519")
			.formParam("thisstep", "18")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709805")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance519", "1")
			.formParam("relevanceG17", "1")
			.formParam("289647X247X519", anws(17))
			.formParam("lastgroup", "289647X247")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_21")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X248X520")
			.formParam("thisstep", "19")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709808")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance520", "1")
			.formParam("relevanceG18", "1")
			.formParam("289647X248X520", anws(18))
			.formParam("lastgroup", "289647X248")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_22")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X249X521")
			.formParam("thisstep", "20")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709812")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance521", "1")
			.formParam("relevanceG19", "1")
			.formParam("289647X249X521", "pokemon")
			.formParam("lastgroup", "289647X249")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_23")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X250X522")
			.formParam("thisstep", "21")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709817")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance522", "1")
			.formParam("relevanceG20", "1")
			.formParam("289647X250X522", anws(19))
			.formParam("lastgroup", "289647X250")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_24")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X251X523")
			.formParam("thisstep", "22")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709820")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance523", "1")
			.formParam("relevanceG21", "1")
			.formParam("289647X251X523", anws(20))
			.formParam("lastgroup", "289647X251")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_25")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X252X524")
			.formParam("thisstep", "23")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709823")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance524", "1")
			.formParam("relevanceG22", "1")
			.formParam("289647X252X524", anws(21))
			.formParam("lastgroup", "289647X252")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_26")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X253X525")
			.formParam("thisstep", "24")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709826")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance525", "1")
			.formParam("relevanceG23", "1")
			.formParam("289647X253X525", anws(22))
			.formParam("lastgroup", "289647X253")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_27")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X254X526")
			.formParam("thisstep", "25")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709829")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance526", "1")
			.formParam("relevanceG24", "1")
			.formParam("289647X254X526", anws(23))
			.formParam("lastgroup", "289647X254")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)
		.exec(http("request_28")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X255X527")
			.formParam("thisstep", "26")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709832")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance527", "1")
			.formParam("relevanceG25", "1")
			.formParam("289647X255X527", anws(24))
			.formParam("lastgroup", "289647X255")
			.formParam("move", "movenext")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_29")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X256X528")
			.formParam("thisstep", "27")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709835")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance528", "1")
			.formParam("relevanceG26", "1")
			.formParam("289647X256X528", anws(25))
			.formParam("lastgroup", "289647X256")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)
		.exec(http("request_30")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X257X529")
			.formParam("thisstep", "28")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709838")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance529", "1")
			.formParam("relevanceG27", "1")
			.formParam("289647X257X529", anws(26))
			.formParam("lastgroup", "289647X257")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_31")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X258X530")
			.formParam("thisstep", "29")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709841")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance530", "1")
			.formParam("relevanceG28", "1")
			.formParam("289647X258X530", anws(27))
			.formParam("lastgroup", "289647X258")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_32")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X259X531")
			.formParam("thisstep", "30")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709844")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance531", "1")
			.formParam("relevanceG29", "1")
			.formParam("289647X259X531", anws(28))
			.formParam("lastgroup", "289647X259")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_33")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X260X532")
			.formParam("thisstep", "31")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709848")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance532", "1")
			.formParam("relevanceG30", "1")
			.formParam("289647X260X532", anws(29))
			.formParam("lastgroup", "289647X260")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_34")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X261X533")
			.formParam("thisstep", "32")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709851")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance533", "1")
			.formParam("relevanceG31", "1")
			.formParam("289647X261X533", anws(30))
			.formParam("lastgroup", "289647X261")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_35")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X262X534")
			.formParam("thisstep", "33")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709854")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance534", "1")
			.formParam("relevanceG32", "1")
			.formParam("289647X262X534", anws(31))
			.formParam("lastgroup", "289647X262")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_36")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X263X535")
			.formParam("thisstep", "34")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709856")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance535", "1")
			.formParam("relevanceG33", "1")
			.formParam("289647X263X535", anws(32))
			.formParam("lastgroup", "289647X263")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_37")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X264X536")
			.formParam("thisstep", "35")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709860")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance536", "1")
			.formParam("relevanceG34", "1")
			.formParam("289647X264X536", anws(33))
			.formParam("lastgroup", "289647X264")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_38")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X265X537")
			.formParam("thisstep", "36")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709865")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance537", "1")
			.formParam("relevanceG35", "1")
			.formParam("289647X265X537", anws(34))
			.formParam("lastgroup", "289647X265")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		).pause(5.seconds,20.seconds)

		.exec(http("request_39")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X266X538")
			.formParam("thisstep", "37")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709868")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance538", "1")
			.formParam("relevanceG36", "1")
			.formParam("289647X266X538", anws(35))
			.formParam("lastgroup", "289647X266")
			.formParam("move", "movenext")
			.formParam("ajax", "off")
			.check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
		)
		.exec(http("request_40")
			.post(config.getString("url_post"))
			.formParam("YII_CSRF_TOKEN", "${YII}")
			.formParam("fieldnames", "289647X269X540")
			.formParam("thisstep", "38")
			.formParam("sid", "289647")
			.formParam("start_time", "1604709868")
			.formParam("LEMpostKey", "${LEMpostKey}")
			.formParam("token", "${token}")
			.formParam("relevance540", "1")
			.formParam("relevanceG37", "1")
			.formParam("289647X269X540", "")
			.formParam("lastgroup", "289647X266")
			.formParam("move", "movesubmit")
		  .formParam("ajax", "off")
		)

	setUp(scn.inject(atOnceUsers(config.getString("n_user").toInt))).protocols(httpProtocol)
}