package computerdatabase

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.util.Random
import scala.collection.mutable.ArrayBuffer

import scala.concurrent.duration._
import java.io.File

import com.typesafe.config.{Config, ConfigFactory}

class BasicSimulation extends Simulation {

  val config = ConfigFactory.parseFile(new File("src/test/resources/data.conf"))

  val anws = ArrayBuffer[String]()

  def patern_anws() ={
    val src = scala.io.Source.fromFile("src/test/resources/anwser_patern.csv").getLines
    val headerLine = src.take(1).next

    for(l <- src) {
      // split line by comma and process them
      l.split(",").map { c =>
        anws+= c.toString
      }
    }
  }


  def rand_anws(): String = {
    var answers = Array("1", "2", "3", "4")
    var random_answer = "A" + answers(Random.nextInt(answers.length))
    return random_answer.toString
  }
  def rand_feed_anws()={
    for( w <- 0 to 100){
      anws+= rand_anws()
    }
  }

  if(config.getString("anw_rand").toInt== 0){
    patern_anws()
  }else{
    rand_feed_anws()
  }


  println(anws(1))
  println(anws(2))
  println(anws(3))


  var question_counter_offset = 2
  val nbUsers = Integer.getInteger("users", 1)
  val nbDuration = Integer.getInteger("Dmaxduration", 60)

  val httpProtocol = http
    .baseUrl(config.getString("url_base"))
    .userAgentHeader("Apache-HttpClient/4.5.5 (Java/1.8.0_191)")
    .header("Connection", "keep-alive")
    .disableCaching // no caching

  val scn = scenario("TestToEnd")
    .feed(csv("tokens_976812.csv").queue)
    //.feed(csv("anwser_patern.csv"))
    .exec(flushCookieJar) // flush all cookies

    .exec(http("recover_token")
      .get(config.getString("url_post"))
      .check(css("input[name=\"YII_CSRF_TOKEN\"]","value").saveAs("YII"))
      .check(status.is(200))
    ).pause(5.seconds,20.seconds)

    .exec(http("login")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("token", "${token}")
      .formParam("continue", "continue")
    ).pause(5.seconds,20.seconds)

    .exec(http("recover_data_lime")
      .get(config.getString("url_post"))
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
      .check(css("#sid","value").saveAs("SID"))
    ).pause(5.seconds,20.seconds)

    .exec(http("terms")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "")
      .formParam("sid", "${SID}")
      .formParam("lastgroupname", "_WELCOME_SCREEN_")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("thisstep", "0")
      .formParam("token", "${token}")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#start_time","value").saveAs("start_time"))
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
      .check(css("#fieldnames","value").saveAs("fieldnames"))
      .check(css("input[name=\"YII_CSRF_TOKEN\"]","value").saveAs("YII"))
    ).pause(5.seconds,20.seconds)



    .exec(http("request_3")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X1X1")
      .formParam("thisstep", "1")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477071")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance1", "1")
      .formParam("relevanceG0", "1")
      .formParam("976812X1X1", anws(1))
      .formParam("lastgroup", "976812X1")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)

    .exec(http("request_4")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X2X2")
      .formParam("thisstep", "2")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477080")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance2", "1")
      .formParam("relevanceG1", "1")
      .formParam("976812X2X2", "Pokemon")
      .formParam("lastgroup", "976812X2")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
      ).pause(5.seconds,20.seconds)
    .exec(http("request_5")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X3X3")
      .formParam("thisstep", "3")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477083")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance3", "1")
      .formParam("relevanceG2", "1")
      .formParam("976812X3X3", anws(2))
      .formParam("lastgroup", "976812X3")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_6")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X4X4")
      .formParam("thisstep", "4")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477085")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance4", "1")
      .formParam("relevanceG3", "1")
      .formParam("976812X4X4", anws(3))
      .formParam("lastgroup", "976812X4")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_7")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X5X5")
      .formParam("thisstep", "5")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477087")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance5", "1")
      .formParam("relevanceG4", "1")
      .formParam("976812X5X5", anws(4))
      .formParam("lastgroup", "976812X5")
      .formParam("move", "movenext")
      .formParam("ajax", "off").check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_8")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X6X6")
      .formParam("thisstep", "6")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477089")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance6", "1")
      .formParam("relevanceG5", "1")
      .formParam("976812X6X6", anws(5))
      .formParam("lastgroup", "976812X6")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_9")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X7X7")
      .formParam("thisstep", "7")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477091")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance7", "1")
      .formParam("relevanceG6", "1")
      .formParam("976812X7X7", anws(6))
      .formParam("lastgroup", "976812X7")
      .formParam("move", "movenext")
      .formParam("ajax", "off").check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_10")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X8X8")
      .formParam("thisstep", "8")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477094")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance8", "1")
      .formParam("relevanceG7", "1")
      .formParam("976812X8X8", anws(7))
      .formParam("lastgroup", "976812X8")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_11")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X9X9")
      .formParam("thisstep", "9")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477096")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance9", "1")
      .formParam("relevanceG8", "1")
      .formParam("976812X9X9", anws(8))
      .formParam("lastgroup", "976812X9")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_12")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X10X10")
      .formParam("thisstep", "10")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477097")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance10", "1")
      .formParam("relevanceG9", "1")
      .formParam("976812X10X10", anws(9))
      .formParam("lastgroup", "976812X10")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_13")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X11X11")
      .formParam("thisstep", "11")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477100")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance11", "1")
      .formParam("relevanceG10", "1")
      .formParam("976812X11X11", anws(10))
      .formParam("lastgroup", "976812X11")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_14")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X12X12")
      .formParam("thisstep", "12")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477102")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance12", "1")
      .formParam("relevanceG11", "1")
      .formParam("976812X12X12", anws(11))
      .formParam("lastgroup", "976812X12")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X13X13")
      .formParam("thisstep", "13")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477102")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance13", "1")
      .formParam("relevanceG12", "1")
      .formParam("976812X13X13", anws(12))
      .formParam("lastgroup", "976812X13")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_15")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X14X14")
      .formParam("thisstep", "14")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477107")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance14", "1")
      .formParam("relevanceG13", "1")
      .formParam("976812X14X14", anws(13))
      .formParam("lastgroup", "976812X14")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_16")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X15X15")
      .formParam("thisstep", "15")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477110")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance15", "1")
      .formParam("relevanceG14", "1")
      .formParam("976812X15X15", anws(14))
      .formParam("lastgroup", "976812X15")
      .formParam("move", "movenext")
      .formParam("ajax", "off").check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_17")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X16X16")
      .formParam("thisstep", "16")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477112")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance16", "1")
      .formParam("relevanceG15", "1")
      .formParam("976812X16X16", anws(15))
      .formParam("lastgroup", "976812X16")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_18")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X17X17")
      .formParam("thisstep", "17")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477114")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance17", "1")
      .formParam("relevanceG16", "1")
      .formParam("976812X17X17", anws(16))
      .formParam("lastgroup", "976812X17")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_19")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X18X18")
      .formParam("thisstep", "18")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477116")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance18", "1")
      .formParam("relevanceG17", "1")
      .formParam("976812X18X18", anws(17))
      .formParam("lastgroup", "976812X18")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_20")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X19X19")
      .formParam("thisstep", "19")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477119")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance19", "1")
      .formParam("relevanceG18", "1")
      .formParam("976812X19X19", anws(18))
      .formParam("lastgroup", "976812X19")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_21")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X20X20")
      .formParam("thisstep", "20")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477121")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance20", "1")
      .formParam("relevanceG19", "1")
      .formParam("976812X20X20", anws(20))
      .formParam("lastgroup", "976812X20")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(3)
    .exec(http("request_22")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X21X21")
      .formParam("thisstep", "21")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477123")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance21", "1")
      .formParam("relevanceG20", "1")
      .formParam("976812X21X21", anws(21))
      .formParam("lastgroup", "976812X21")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_23")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X23X23")
      .formParam("thisstep", "22")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477126")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance23", "1")
      .formParam("relevanceG21", "1")
      .formParam("976812X23X23", anws(22))
      .formParam("lastgroup", "976812X23")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_23")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X25X25")
      .formParam("thisstep", "23")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477126")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance25", "1")
      .formParam("relevanceG22", "1")
      .formParam("976812X25X25", anws(23))
      .formParam("lastgroup", "976812X25")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_25")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X27X27")
      .formParam("thisstep", "24")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477131")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance27", "1")
      .formParam("relevanceG23", "1")
      .formParam("976812X27X27", anws(24))
      .formParam("lastgroup", "976812X27")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_26")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X29X29")
      .formParam("thisstep", "25")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477134")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance29", "1")
      .formParam("relevanceG24", "1")
      .formParam("976812X29X29", anws(25))
      .formParam("lastgroup", "976812X29")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_27")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X31X31")
      .formParam("thisstep", "26")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477135")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance31", "1")
      .formParam("relevanceG25", "1")
      .formParam("976812X31X31", anws(26))
      .formParam("lastgroup", "976812X31")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_28")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X33X33")
      .formParam("thisstep", "27")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477137")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance33", "1")
      .formParam("relevanceG26", "1")
      .formParam("976812X33X33", anws(27))
      .formParam("lastgroup", "976812X33")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_29")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X35X35")
      .formParam("thisstep", "28")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477139")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance35", "1")
      .formParam("relevanceG27", "1")
      .formParam("976812X35X35", anws(28))
      .formParam("lastgroup", "976812X35")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_30")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X37X37")
      .formParam("thisstep", "29")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477141")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance37", "1")
      .formParam("relevanceG28", "1")
      .formParam("976812X37X37", anws(29))
      .formParam("lastgroup", "976812X37")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_31")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X39X39")
      .formParam("thisstep", "30")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477144")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance39", "1")
      .formParam("relevanceG29", "1")
      .formParam("976812X39X39", anws(30))
      .formParam("lastgroup", "976812X39")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_32")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X41X41")
      .formParam("thisstep", "31")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477146")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance41", "1")
      .formParam("relevanceG30", "1")
      .formParam("976812X41X41", anws(31))
      .formParam("lastgroup", "976812X41")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_33")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X43X43")
      .formParam("thisstep", "32")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477148")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance43", "1")
      .formParam("relevanceG31", "1")
      .formParam("976812X43X43", anws(32))
      .formParam("lastgroup", "976812X43")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)

    .exec(http("request_36")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X45X45")
      .formParam("thisstep", "33")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477151")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance45", "1")
      .formParam("relevanceG32", "1")
      .formParam("976812X45X45", anws(33))
      .formParam("lastgroup", "976812X45")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_37")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X47X47")
      .formParam("thisstep", "34")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477154")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance47", "1")
      .formParam("relevanceG33", "1")
      .formParam("976812X47X47", anws(34))
      .formParam("lastgroup", "976812X47")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_38")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X49X49")
      .formParam("thisstep", "35")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477156")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance49", "1")
      .formParam("relevanceG34", "1")
      .formParam("976812X49X49", anws(35))
      .formParam("lastgroup", "976812X49")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_39")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X51X51")
      .formParam("thisstep", "36")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477158")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance51", "1")
      .formParam("relevanceG35", "1")
      .formParam("976812X51X51", anws(36))
      .formParam("lastgroup", "976812X51")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_40")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X53X53")
      .formParam("thisstep", "37")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477161")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance53", "1")
      .formParam("relevanceG36", "1")
      .formParam("976812X53X53", anws(37))
      .formParam("lastgroup", "976812X53")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_41")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X55X55")
      .formParam("thisstep", "38")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477163")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance55", "1")
      .formParam("relevanceG37", "1")
      .formParam("976812X55X55", anws(38))
      .formParam("lastgroup", "976812X55")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_42")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X57X57")
      .formParam("thisstep", "39")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477165")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance57", "1")
      .formParam("relevanceG38", "1")
      .formParam("976812X57X57", anws(39))
      .formParam("lastgroup", "976812X57")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_43")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X59X59")
      .formParam("thisstep", "40")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477167")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance59", "1")
      .formParam("relevanceG39", "1")
      .formParam("976812X59X59", anws(40))
      .formParam("lastgroup", "976812X59")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_44")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X22X22")
      .formParam("thisstep", "41")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477169")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance22", "1")
      .formParam("relevanceG40", "1")
      .formParam("976812X22X22", anws(41))
      .formParam("lastgroup", "976812X22")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_45")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X24X24")
      .formParam("thisstep", "42")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477171")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance24", "1")
      .formParam("relevanceG41", "1")
      .formParam("976812X24X24", anws(42))
      .formParam("lastgroup", "976812X24")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_45")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X26X26")
      .formParam("thisstep", "43")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477171")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance26", "1")
      .formParam("relevanceG42", "1")
      .formParam("976812X26X26", anws(43))
      .formParam("lastgroup", "976812X26")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)

    .exec(http("request_47")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X28X28")
      .formParam("thisstep", "44")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477176")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance28", "1")
      .formParam("relevanceG43", "1")
      .formParam("976812X28X28", anws(44))
      .formParam("lastgroup", "976812X28")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_48")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X30X30")
      .formParam("thisstep", "45")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477178")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance30", "1")
      .formParam("relevanceG44", "1")
      .formParam("976812X30X30", anws(45))
      .formParam("lastgroup", "976812X30")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_49")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X32X32")
      .formParam("thisstep", "46")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477181")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance32", "1")
      .formParam("relevanceG45", "1")
      .formParam("976812X32X32", anws(46))
      .formParam("lastgroup", "976812X32")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_50")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X34X34")
      .formParam("thisstep", "47")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477184")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance34", "1")
      .formParam("relevanceG46", "1")
      .formParam("976812X34X34", anws(47))
      .formParam("lastgroup", "976812X34")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_51")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X36X36")
      .formParam("thisstep", "48")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477187")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance36", "1")
      .formParam("relevanceG47", "1")
      .formParam("976812X36X36", anws(48))
      .formParam("lastgroup", "976812X36")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_52")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X38X38")
      .formParam("thisstep", "49")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477189")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance38", "1")
      .formParam("relevanceG48", "1")
      .formParam("976812X38X38", anws(49))
      .formParam("lastgroup", "976812X38")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_53")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X40X40")
      .formParam("thisstep", "50")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477191")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance40", "1")
      .formParam("relevanceG49", "1")
      .formParam("976812X40X40", anws(50))
      .formParam("lastgroup", "976812X40")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_54")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X42X42")
      .formParam("thisstep", "51")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477193")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance42", "1")
      .formParam("relevanceG50", "1")
      .formParam("976812X42X42", anws(51))
      .formParam("lastgroup", "976812X42")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_55")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X44X44")
      .formParam("thisstep", "52")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477195")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance44", "1")
      .formParam("relevanceG51", "1")
      .formParam("976812X44X44", anws(52))
      .formParam("lastgroup", "976812X44")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)

    .exec(http("request")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X46X46")
      .formParam("thisstep", "53")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477195")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance46", "1")
      .formParam("relevanceG52", "1")
      .formParam("976812X46X46", anws(53))
      .formParam("lastgroup", "976812X46")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)

    .exec(http("request_56")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X48X48")
      .formParam("thisstep", "54")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477202")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance48", "1")
      .formParam("relevanceG53", "1")
      .formParam("976812X48X48", anws(53))
      .formParam("lastgroup", "976812X48")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)


    .exec(http("request_57")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X50X50")
      .formParam("thisstep", "55")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477205")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance50", "1")
      .formParam("relevanceG54", "1")
      .formParam("976812X50X50", anws(54))
      .formParam("lastgroup", "976812X50")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_58")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X52X52")
      .formParam("thisstep", "56")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477207")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance52", "1")
      .formParam("relevanceG55", "1")
      .formParam("976812X52X52", anws(55))
      .formParam("lastgroup", "976812X52")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_59")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X54X54")
      .formParam("thisstep", "57")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477210")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance54", "1")
      .formParam("relevanceG56", "1")
      .formParam("976812X54X54", anws(56))
      .formParam("lastgroup", "976812X54")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_60")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X56X56")
      .formParam("thisstep", "58")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477211")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance56", "1")
      .formParam("relevanceG57", "1")
      .formParam("976812X56X56", anws(57))
      .formParam("lastgroup", "976812X56")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_61")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X58X58")
      .formParam("thisstep", "59")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477213")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance58", "1")
      .formParam("relevanceG58", "1")
      .formParam("976812X58X58", anws(58))
      .formParam("lastgroup", "976812X58")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)
    .exec(http("request_62")
      .post(config.getString("url_post"))
      .formParam("YII_CSRF_TOKEN", "${YII}")
      .formParam("fieldnames", "976812X60X60")
      .formParam("thisstep", "60")
      .formParam("sid", "976812")
      .formParam("start_time", "1603477215")
      .formParam("LEMpostKey", "${LEMpostKey}")
      .formParam("token", "${token}")
      .formParam("relevance60", "1")
      .formParam("relevanceG59", "1")
      .formParam("976812X60X60", anws(59))
      .formParam("lastgroup", "976812X60")
      .formParam("move", "movenext")
      .formParam("ajax", "off")
      .check(css("#LEMpostKey","value").saveAs("LEMpostKey"))
    ).pause(5.seconds,20.seconds)

    //.exec(http("request_63")
    //  .post(config.getString("url_post"))
    //  .formParam("YII_CSRF_TOKEN", "${YII}")
    //  .formParam("fieldnames", "976812X61X61")
    //  .formParam("thisstep", "61")
    //  .formParam("sid", "976812")
    //  .formParam("start_time", "1603477216")
    //  .formParam("LEMpostKey", "${LEMpostKey}")
    //  .formParam("token", "${token}")
    //  .formParam("relevance61", "1")
    //  .formParam("relevanceG60", "1")
    //  .formParam("976812X61X61", "")
    //  .formParam("lastgroup", "976812X61")
    //  .formParam("move", "movesubmit")
    //  .formParam("ajax", "off"))


  setUp(scn.inject(atOnceUsers(config.getString("n_user").toInt)).protocols(httpProtocol))
}
